// client/src/pages/AuthPage.vue
<script lang="ts">
import LoginForm from '@/components/Auth/LoginForm.vue';
import RegForm from '@/components/Auth/RegForm.vue';
import { defineComponent } from 'vue';
import '@/styles/authPage.scss';

export default defineComponent({
    data: () => ({
        isRegistration: false,
    }),
    components: { LoginForm, RegForm },
});
</script>

<template>
    <a-row justify="center">
        <a-col :span="12">
            <div v-if="!isRegistration">
                <h4 class="text-center mb-4">Authorization</h4>
                <LoginForm />
            </div>
            <div v-else>
                <h4 class="text-center mb-4">Registration for your company</h4>
                <RegForm />
            </div>

            <a-row justify="end">
                <a-switch
                    v-model:checked="isRegistration"
                    checked-children="Registration"
                    un-checked-children="Authorization"
                />
            </a-row>
        </a-col>
    </a-row>
</template>

<style scoped></style>

// client/src/pages/AuthPage.tsx
import React, { FC, useState } from "react";
import { Row, Card, Container } from "react-bootstrap";
import LoginForm from "../components/LoginForm";
import RegForm from "../components/RegForm";
import Switcher from "../components/UI/Switcher";
import "../styles/authForms.scss";

const AuthPage = () => {
    const [isLogin, setLogin] = useState(true);
    return (
        <Container>
            <Row className="h100 d-flex justify-content-center align-items-center auth-forms">
                <Card className="h-60 p-4 w-50">
                    <h1 className="text-center mt-3">Log in as company</h1>
                    <div className="mt-3">
                        <Switcher
                            left="Login"
                            right="Register"
                            setValue={setLogin}
                            value={isLogin}
                        />
                    </div>
                    {isLogin ? <LoginForm /> : <RegForm />}
                </Card>
            </Row>
        </Container>
    );
};
export default AuthPage;
